### ISSUE TITLE
[BUG] Stripe "You did not provide an API key" on donate form payment

### ISSUE THREAD

**Issue by BenSturmfels** [houdiniproject/houdini#1050]
After configuring my local development environment with `STRIPE_API_KEY` and `STRIPE_API_PUBLIC` and adding some `puts` into `gems/bess/lib/houdini/engine.rb` to verify tha the environment variables are being being read in, I'm seeing the a "You did not provide an API key" error on the donate form (screenshot below).

![2022-03-17_10-01](https://user-images.githubusercontent.com/9541562/158705840-83cbf8fb-dc30-4fa7-922a-a55d9ecb128a.png)

From what I can see in the browser console, the `Authorization: Bearer` header is missing the the API key on the end, e.g. `Authorization: Bearer XXX`.

This is running against master in development mode, Ruby 2.7.4 and allowing assets to be built in-process (not a separate webpack process).

**Comment by BenSturmfels** [comment]
(The Internal Server Error in my console are unrelated errors loading images caused by missing `libvips.so.42`)

**Comment by BenSturmfels** [comment]
If I modify `bess` like this:

```patch
diff --git a/gems/bess/lib/houdini/engine.rb b/gems/bess/lib/houdini/engine.rb
index ddb499f4..fc6ef5b0 100644
--- a/gems/bess/lib/houdini/engine.rb
+++ b/gems/bess/lib/houdini/engine.rb
@@ -34,6 +34,8 @@ module Houdini
     config.houdini.payment_providers.stripe = ActiveSupport::OrderedOptions.new
     config.houdini.payment_providers.stripe.public_key = ENV['STRIPE_API_PUBLIC']
     config.houdini.payment_providers.stripe.private_key = ENV['STRIPE_API_KEY']
+    puts config.houdini.payment_providers.stripe.private_key
+    puts config.houdini.payment_providers.stripe.public_key
     config.houdini.payment_providers.stripe.connect = false
     config.houdini.payment_providers.stripe.proprietary_v2_js = false
```

and start `bin/rails server`, I see my Stripe keys printed to the console.

Then if I modify `_javascripts.html.erb` like this:

```patch
diff --git a/app/views/layouts/_javascripts.html.erb b/app/views/layouts/_javascripts.html.erb
index 5c724dc5..4c8ba88d 100644
--- a/app/views/layouts/_javascripts.html.erb
+++ b/app/views/layouts/_javascripts.html.erb
@@ -8,6 +8,9 @@
   <%= javascript_pack_tag "page__stripe_wrapper" %>
 <% end %>
 
+<pre>Debug 1: <%= Houdini.payment_providers.stripe %></pre>
+<pre>Debug 2: <%= Houdini.payment_providers.stripe.public_key %></pre>
+
 <script>
 Stripe.setPublishableKey("<%= Houdini.payment_providers.stripe.public_key %>");
 window._csrf = "<%= form_authenticity_token %>";
```

and view the dashboard page, I see:

```HTML
<pre>Debug 1: #&lt;Houdini::PaymentProvider::StripeProvider:0x00007f2d596e1b48&gt;</pre>
<pre>Debug 2: </pre>
```

**Comment by BenSturmfels** [comment]
If I forge ahead by hard-coding my Stripe public key and submit the credit card form, the authorization header is all good and the POST to api.stripe.com succeeds, but I then get a 404 on `http://localhost:5000/cards` and `Uncaught TypeError: resp is undefined`. See screenshot:

![2022-03-23_17-09](https://user-images.githubusercontent.com/9541562/159635057-033f0609-fd78-483d-a82d-cd5cc07077a1.png)

**Comment by BenSturmfels** [comment]
If I do the same as above (temporarily hard-code public key) while logged into the dashboard, I get at error from the Stripe API:

`Received unknown parameter: card[profile_id]"`

**Comment by wwahammy** [comment]
I think these are two separate issues. Would you be able to separate them?

**Comment by wwahammy** [comment]
This may relate to your second bug or it may not. https://github.com/houdiniproject/houdini/pull/1066

**Comment by BenSturmfels** [comment]
Sure, it may well be three separate issues, so I'll break them out. Just didn't want to create too much noise.

**Comment by BenSturmfels** [comment]
Confirming that the "You did not provide an API key" issue is fixed by PR #1066. No change for the other two, but they're now in separate issues.

**Comment by wwahammy** [comment]
@BenSturmfels: am I correct that we can close this issue?

**Comment by wwahammy** [comment]
Ah, fair point!
