### ISSUE TITLE
[BUG] Stuck "Loading..." overlay and JS error "Stripe is not defined" when assets built with `NODE_ENV=production`

### ISSUE THREAD

**Issue by BenSturmfels** [houdiniproject/houdini#1060]
On the `main` branch, when I pre-build the assets with `rm -rf public/packs && bin/rake assets:precompile`, the Houdini dashboard get stuck with a greyed out "Loading..."  overlay and the following JS console errors:

```
ReferenceError: Stripe is not defined
ReferenceError: appl is not defined
Uncaught ReferenceError: I18n is not defined
```

![2022-03-23_12-34](https://user-images.githubusercontent.com/9541562/159606018-cd8f882a-445e-47d3-ae10-dec9b3eb3e08.png)

If instead I `rm -rf public/packs` and run up the development server and let it build the assets, the dashboard loads with no issues. Similarly no issues if I `rm -rf public/packs && NODE_ENV=development bin/rake assets:precompile`. The difference between the 

The seems independent of whether I'm running the development server or the production server (with removed font-assets and `config.reload_routes = false` as per #1046 and #1054 to allow production to start).

The `page__strip_wrapper` JS file where `Stripe` is defined *is* being loaded, as shown in the above screenshot and it seems to be loaded before the error occurs. It seems that either the `page__strip_wrapper` JS isn't running or is being broken somehow by the production Webpack build process. I tried adding a `console.log('Hello from Stripe!')` at the bottom of `app/javascript/legacy/stripe_wrapper/index.es6` and rebuilding. The console message showed up for the inline development build, but not for the `assets:precompile` build.

I found that removing the `environment.SplitChunks` block from `config/webpack/production.js` and building with `rm -rf public/packs && bin/rake assets:precompile` also works, so the issue would appear to be related to chunking.

**Comment by wwahammy** [comment]
So I doubt this is the problem but one thing you should consider is you shouldn't use `bin/rake`. Since at least version 6, rake tasks can be called via `bin/rails`.

**Comment by wwahammy** [comment]
I think I know the problem here, let me verify
