### ISSUE TITLE
[BUG] Missing translations on Donate Form in dev

### ISSUE THREAD

**Issue by BenSturmfels** [houdiniproject/houdini#1061]
(Transferring this from Discussion #1048  to an Issue not that @wwahammy has confirmed it's an issue. Sorry, appears that the "Create issue from discussion" button only transfers the first post".)

<div type='discussions-op-text'>

<sup>Originally posted by **BenSturmfels** March 16, 2022</sup>
Hi Folks,
After running up a development environment as per the README.md, if I go to the "Donate Form Builder" and click on the blue "Donate" button, I see a form that has lots of text like:

`[missing "en.nonprofits.donate.payment.card.submit" translation]`

![Screen Shot 2022-03-16 at 17 29 46](https://user-images.githubusercontent.com/9541562/158530043-1734e156-b252-4fce-ae1f-5a41e062a7e0.png)

Have I missed a step somewhere?</div>

**Comment by wwahammy** [comment]
I think I know what's going on here but it's going to take a bit to fix. I'll try to get to it this week.
