### ISSUE TITLE
[FEATURE] Meaningful variables names

### ISSUE THREAD

**Issue by JoaoVitorFarias** [houdiniproject/houdini#1081]
**Is your feature request related to a problem? Please describe.**
I came across some variables that have not names meaningful, so that make the code less readable.

**Describe the solution you'd like**
I thought of some alternatives:
[```npo```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/nonprofits/bank_accounts_controller.rb#L30) -> ```nonprofit```
[```ba```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/nonprofits/bank_accounts_controller.rb#L31) -> ```bank_account```
[```tok```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/users/sessions_controller.rb#L24) -> ```token```
[```acct```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/cards_controller.rb#L10) -> ```account```
[```es```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/email_settings_controller.rb#L12) -> ```email_settings```
[```ev```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/events_controller.rb#L42) -> ```event```
[```rd```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/recurring_donations_controller.rb#L47) -> ```recurring_donation```
[```np```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/super_admins_controller.rb#L66) -> ```nonprofit```
[```ev_id```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/ticket_levels_controller.rb#L12) -> ```event_id```

Some of these variables changes were pointed in the issue #797
I would like to know what you think and if it is ok, I can work on that.

**Comment by clarissalimab** [comment]
@wwahammy I'm always in favor of using the entire name instead of abbreviations, I think the benefit of clarity overcomes the benefit of typing less letters, and it also makes it easier to be searched. But that's just my personal opinion =)
