### ISSUE TITLE
[BUG] PaymentNotificationEmailDonorJob fails due to missing locale

### ISSUE THREAD

**Issue by BenSturmfels** [houdiniproject/houdini#1139]
Relating to PR #1115, `PaymentNotificationEmailDonorJob` silently fails in development when run by GoodJob. Two issues here are firstly that the payment notification email doesn't get sent in development and secondly that the error is being swallowed silently in development - this should fail in an obvious way.

The error appears to be `payment_mailer.rb:22` not passing the required locale to the `PaymentNotificationEmailDonorJob`.

**Comment by BenSturmfels** [comment]
@wwahammy I've love to got your thoughts on this one. Currently when I make a credit card campaign donation on our production-like demo instance and run `bundle exec good_job start` some job details are shown, but there's no error and no payment confirmation email is sent:

```
$ bundle exec good_job start
/srv/houdini/.gems/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/srv/houdini/.gems/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/srv/houdini/.gems/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: already initialized constant Net::NetPrivate::Socket
/usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
[GoodJob] [2347918] GoodJob 3.15.13 started scheduler with queues=* max_threads=5.
[GoodJob] Notifier subscribed with LISTEN
[GoodJob] [2347918] [GoodJob::Scheduler(queues=* max_threads=5)-thread-4] Executed GoodJob a8713150-a2a5-4992-81b2-f027fd82872e
[GoodJob] [2347918] [GoodJob::Scheduler(queues=* max_threads=5)-thread-3] Executed GoodJob baec9b00-8b45-463f-a19b-657b065c9d6a
[GoodJob] [2347918] [GoodJob::Scheduler(queues=* max_threads=5)-thread-1] Executed GoodJob e7bd7b0e-66ec-4ec7-82d6-8b05e596b7f7
[GoodJob] [2347918] [GoodJob::Scheduler(queues=* max_threads=5)-thread-2] Executed GoodJob 88449c68-f669-4ea7-85f9-419167ceeb84
[GoodJob] [2347918] [GoodJob::Scheduler(queues=* max_threads=5)-thread-5] Executed GoodJob 43f878ac-d26e-4df9-b1f9-868d28658c8d
```

It does seem to briefly open a connection to the local MTA, but nothing is sent:

$ sudo tail -f /var/log/mail.log
Jun 26 11:15:58 donationtest postfix/smtpd[2347818]: connect from localhost[127.0.0.1]
Jun 26 11:15:58 donationtest postfix/smtpd[2347815]: connect from localhost[127.0.0.1]
Jun 26 11:15:58 donationtest postfix/smtpd[2347815]: SSL_accept error from localhost[127.0.0.1]: -1
Jun 26 11:15:58 donationtest postfix/smtpd[2347818]: SSL_accept error from localhost[127.0.0.1]: -1
Jun 26 11:15:58 donationtest postfix/smtpd[2347818]: warning: TLS library problem: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1543:SSL alert number 80:
Jun 26 11:15:58 donationtest postfix/smtpd[2347818]: lost connection after STARTTLS from localhost[127.0.0.1]
Jun 26 11:15:58 donationtest postfix/smtpd[2347818]: disconnect from localhost[127.0.0.1] ehlo=1 starttls=0/1 commands=1/2
Jun 26 11:15:58 donationtest postfix/smtpd[2347815]: warning: TLS library problem: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1543:SSL alert number 80:
Jun 26 11:15:58 donationtest postfix/smtpd[2347815]: lost connection after STARTTLS from localhost[127.0.0.1]
Jun 26 11:15:58 donationtest postfix/smtpd[2347815]: disconnect from localhost[127.0.0.1] ehlo=1 starttls=0/1 commands=1/2

Other mail like the account activation email sends ok, so the mail setup seems to be fine. It looks as though these activation emails are sent directly though, rather than being queued jobs.

**Comment by BenSturmfels** [comment]
Hey @wwahammy, just FYI this is probably the one remaining blocker we have - payment notification emails aren't being sent.

**Comment by wwahammy** [comment]
Hey @BenSturmfels, I'll work on this.

**Comment by wwahammy** [comment]
Is it supposed to be connecting via TLS to your localhost's email service?

**Comment by wwahammy** [comment]
Could you share the `config.action_mailer` settings you're configuring in your `config/environments/production.rb` file?

**Comment by BenSturmfels** [comment]
@wwahammy good catch - in the example above it was attempting to connect via TLS but failing due to a self-signed certificate. That's addressed now, and emails like "forgot password" go through again as they did at the time I created the issue (June 2022).

The issue with donation receipt emails remains though, so I think that's unrelated.
