### ISSUE TITLE
Add Link for Terms and Conditions and Source download

### ISSUE THREAD

**Issue by ericschultz** [houdiniproject/houdini#12]
We need to add a link for terms and conditions to all pages.

This is needed due to the AGPL's requirement that a source download be available. It must have the following features:
* Include the terms of the AGPL (with webisite template exception)
* Include the any terms of the instance of Houdini, or none if none exist
* Include links to a source code download (ideally created as part of the build process)

Ideally, it should have the following features:
* an elegant way of listing the software used on the site as well as links to learn more about it.
* A link to the commit on a public github/gitlab repo so it would be easy to the user to get involved.

**Comment by tttp** [comment]
Hi,

It is simply not an option to deter the donors with anything that isn't related to the donation. It would be ridiculous that a free software performs worse than a closed source competitor because it's wavering its licence instead of focussing on getting donations ;)

On another aGPL software, there is an option to disable its logo on public pages, so only the admins see it, could it be valid here?

For what I remember, the aGPL simply requires that it is mentioned that it is free software somewhere, and that putting it as a comment on the html on some pages that don't have the space to display a visible notice is good enough.

Would it work here? adding the link on the widget isn't a great option ;)

**Comment by ericschultz** [comment]
We do have to provide it somewhere on a terms and conditions page. I suppose we don't have to provide any info on the iframe but it seems weird that people would be donating and no knowing the rules of the site they're using.

For CommitChange, we were particularly interested in adding a bottom bar that says "Powered by CommtiChange". The idea of adding the terms link is related to that. If it's a not viable we can probably remove that as a requirement of this issue.

**Comment by ericschultz** [comment]
I've removed the "(including embedded iframe)" from the initial issue.

**Comment by ericschultz** [comment]
Another idea, I just thought of: LibreJS uses metadata provided by the site owner to define JS licenses. (I don't remember the details). Combined with comments I think we're doing our part.

**Comment by heyakyra** [comment]
Sorry if this isn't the best place for this question, but what is the `WTO-AP-3.0-or-later` part of the license refer to?

**Comment by wwahammy** [comment]
@heyakyra you're welcome to ask here or on our [Zulip](https://houdini.zulipchat.com/)

`WTO-AP-3.0-or-later` is short for Web Template Output Additional Permission version 3.0 or later. You can see the file at https://github.com/houdiniproject/houdini/blob/main/Web-Template-Output-Additional-Permission.txt. You should also reference our [LICENSE document](https://github.com/houdiniproject/houdini/blob/main/LICENSE) which explains the specific licenses for each type of "output". 

I think some background would be helpful here. When Houdini was going to join Conservancy, the goal was to use the most strongly copyleft license as possible. For the server software, we wanted to use AGPL3+. For the front-end javascript, we settled on LGPL3+. The reason we picked LGPL was that there are use-cases where you may want to included Javascript from an external service, like Google Maps or Stripe's official javascript library, that isn't under a free-software license. From a software freedom perspective, this isn't ideal but it would have been far too limiting to Houdini users to have to give all of those things up.

The additional permission specifies what parts are under the AGPL (Rails backend code) and which parts are under the LGPL (frontend javascript). It also clarifies a few quirky situations that weren't considered for the AGPL and hadn't really been considered for this type of software. For example, what is the license of the HTML that is generated by a Rails template? What is the license of any Javascript that happens to be generated at run time by a Rails template? If we said "everything that is Rails code is under the AGPL", the generated HTML and Javascript would be under the AGPL which would force the entire front-end to be under the AGPL. But as I mentioned before, this was what we wanted to avoid.

The permission written by Conservancy's legal counsel helped us clarify this weird situation: generated HTML, even if it's generated under a Rails template on the server, is licensed under CC0 (public domain). Generated Javascript would always be under LGPL3+.

In the end, it's basically a way to make very clear that the backend code is AGPL and the frontend Javascript is LGPL as everyone expects, even when the frontend is generated.

I have no idea if what I just wrote was clear at all, so don't hesitate to ask for clarification :laughing:. Also, I should be clear, I'm not a lawyer and this isn't legal advice.

It also may be of interest to you that Bradley Kuhn and Karen Sandler who worked with myself and Conservancy's counsel to draft the Web Template Output Additional Permission will be speaking about GPL Exceptions, including the WTO-AP, at State of the Source. It's an online conference organized by the Open Source Initiative. They speak next Thursday and you can find their talk listed at: https://eventyay.com/e/8fa7fd14/schedule?date=2020-09-10

**Comment by heyakyra** [comment]
Ah, I should have looked in the repo before I just did a web search for `WTO-AP-3.0-or-later`! Thanks so much for all of that context, its great to learn and maybe I'll pick this up for some future projects. It would be nice to have a page dedicated to that license somewhere

**Comment by wwahammy** [comment]
> Ah, I should have looked in the repo before I just did a web search for `WTO-AP-3.0-or-later`! 

We used to spell out `AGPL-3.0-or-later WITH Web-Template-Output-Additional-Permission-3.0-or-later` which would make the search way easier. Unfortunately, we realized when we created the Bess gem, that the Ruby Bundler tools don't accept license descriptions of more than 63 characters. Sadly, we had to abbreviate it.

>Thanks so much for all of that context, its great to learn and maybe I'll pick this up for some future projects. It would be nice to have a page dedicated to that license somewhere

Happy to provide the context. That's fantastic that you're considering using it. I was a little surprised that no one had addressed this issue until we stumbled on it. I guess with AGPL not being super highly used and the fact that lots of people can be a little loose with licenses, it apparently hadn't come up.

Also, I totally agree that we should have a page for it! @bkuhn and I were going to write a blog post for Software Freedom Conservancy about it after it was implemented. Sadly, we've kept putting it on the side and haven't gotten back to it. Between this though and Bradley and Karen's talk next week, maybe we'll have to prioritize it more.

Please do stay in touch, we're happy to have you in the Houdini community!
