### ISSUE TITLE
Cron job rake name

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#123]
The name of the cron job runner in Houdini is [`heroku_scheduled_job`](https://github.com/houdiniproject/houdini/blob/2e257aa99d8f8840e2a0fa2676c516cd95437afe/lib/tasks/scheduler.rake). This is due to historical reasons on CommitChange. This name should be made more generic.

**Comment by Giuulob89** [comment]
Hey @wwahammy, I'm Giulia! Me and Murilo, both University of Brasilia students, are excited to contribute with Houdini community and we'd like to start with this issue.

**Comment by wwahammy** [comment]
Hi @Giuulob89, sounds great!
