### ISSUE TITLE
[BUG] Rails spec failing based on local currency

### ISSUE THREAD

**Issue by murilogds** [houdiniproject/houdini#1235]
When running rails spec in systems that uses another default currency (different from "$"), tests that compare money values happens to fail.

## Description

After setting up the project correctly, when i run the `./bin/rails spec` command, some tests fail, this is clearly due to localization issues (in my case i live in Brazil, and brazilian currency is R$). I don't know if it's some postgres configuration or some computer based configuration. I think the tests should consider any possible currency to run correctly.

![Captura de tela de 2022-07-17 18-57-00](https://user-images.githubusercontent.com/48963324/179426490-68bd0a06-3c84-4762-a238-d9b552174fb7.png)
![Captura de tela de 2022-07-17 18-56-51](https://user-images.githubusercontent.com/48963324/179426494-7a260030-1d4c-4768-a31f-a0e059c1e969.png)
![Captura de tela de 2022-07-17 18-56-41](https://user-images.githubusercontent.com/48963324/179426496-47a4f431-528c-41ed-a242-96573c4860c5.png)
![Captura de tela de 2022-07-17 18-56-33](https://user-images.githubusercontent.com/48963324/179426501-57f343c8-3c1b-4454-a244-16ed4680a47c.png)
![Captura de tela de 2022-07-17 18-56-26](https://user-images.githubusercontent.com/48963324/179426513-3c855556-ea5b-464a-b38d-360710508194.png)

## Expected Behavior

* The tests should pass independently of the system currency

## Actual Behavior

* Tests that compares money are failing

## Possible Fix

I don't know if it's a good a ideia, but a possible fix for this issue could be comparing only the value of the money instead of the whole string.

## Steps to Reproduce

**Obs.: The tests only fail in systems that are not configured to use American Dollar as default currency**
1. Set up the project
2. Run `./bin/rails spec`

## Context

This bug happened in the first time I was setting up the project, when the tests failed, my first thought was that something about my set up was wrong and i shoul re-do it. This bug may cause confusion in new contributors to the project from other places in the world.

## Your Environment

* Ruby version: 2.7.6
* Operating System and version: Pop! _OS 20.04

**Comment by murilogds** [comment]
Yes, only those in the images!

**Comment by murilogds** [comment]
> @murilogds thanks for reporting this! Is it only those four tests that fail?

Yes, only the ones in the image!

**Comment by wwahammy** [comment]
@murilogds it's definitely related to the Postgres config. That said, the currency symbol added should be based on the currency of the nonprofit.

Is this something you'd be open to try to fix?

**Comment by murilogds** [comment]
@wwahammy For sure, I'll take this issue with @Giuulob89.
