### ISSUE TITLE
`NonprofitMailer.refund` incorrectly tries to send even if nothing in `to:`

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#1454]
It's possible for the nonprofit to have no users set to receive notifications of payments, i.e. the call on line 23 https://github.com/houdiniproject/houdini/blob/095d28b82bd55fd08cbb140385bd03c5b32b2e68/app/mailers/nonprofit_mailer.rb#L23-L24 returns an empty array. That makes the call to `mail` on line 24 error out (at least if you're using AWS SES) as it's incorrect to send an email with nothing in the "to:" header.

The fix would be to add a guard on line 24 against `@emails` being an empty array.

**Comment by victordscabral** [comment]
Link to the PR: https://github.com/houdiniproject/houdini/pull/1460
