### ISSUE TITLE
Setup multithreading

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#23]
Puma and Rails both supports multithreading. That said, it's not set up in the current code. Additionally, it's not entirely clear that Houdini's code is actually threadsafe. Setting up multithreading may require the following tasks:

* Verify that our code is threadsafe (or close to it)
* Turn on config.threadsafe! in the Rails config (since we use 3.2)
* Set up Puma multithreading (tutorial at https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server)
* Test!

This would be best handled by someone with experience dealing with Rails and multithreading

**Comment by tttp** [comment]
@ericschultz is there a way to validate that houdini is threadsafe? what area/code you suspect being at risk?
