### ISSUE TITLE
[BUG] Settings page throws exception in fresh system

### ISSUE THREAD

**Issue by stevel408** [houdiniproject/houdini#285]
## Description

After I ran the system according to the instructions in the README file, I was able to successfully sign up an organization. But then got the big red error page when I click on the "Settings" menu item.

## Expected Behavior

Some types of setting content would show up.

## Actual Behavior

Big red error page, showing:

```
Showing .../houdini/app/views/settings/_pricing.html.erb where line #10 raised:

undefined method `name' for nil:NilClass

Extracted source (around line #10):
              
<div class='pane-inner'>
	<p><strong>Tier:
    <%= @nonprofit.billing_plan.name %>
    (
    $<%= Format::Currency.cents_to_dollars @nonprofit.billing_plan.amount %> <%= @nonprofit.billing_plan.interval || 'monthly'%>
    <%= @nonprofit.billing_plan.percentage_fee > 0 ? ', ' + (@nonprofit.billing_plan.percentage_fee * 100).round(2).to_s + '%' : '' %>
```

## Possible Fix

Maybe no billing plan yet? a new sign-up should be taken to some place to set up the billing plan first? 

## Steps to Reproduce

Set up a fresh/new system, go to http://localhost:5000, sign up an org, click "Settings"

## Your Environment
* Ruby version: 2.6.6
* Server type and version: Ruby built-in web server
* Operating System and version:  Ubuntu 18.04

**Comment by wwahammy** [comment]
@stevel408 thanks for the bug report! I think you're right about there being no billing plan. I'll look into this more this afternoon.

**Comment by wwahammy** [comment]
@stevel408 I think what's happening is that the original billing plan is not in the database by default.

Is there any information in the database that you'd feel uncomfortable deleting? Ideally, to verify this is the case, we should start from a clean slate.

If you're fine losing everything in the db, I recommend you run the following at the command line:
```bash
bin/rails db:drop # deletes the database
bin/setup
bin/rails db:seed
```
After you do that, register your nonprofit again and try to go to the Settings. It's possible there's other stuff that doesn't work there but let me know if you still get the same error. If you don't, I'll submit a PR to add `db:seed` to the `bin/setup` script.

**Comment by stevel408** [comment]
Thanks Eric for the tips, I guess it's a bit more complicated than that. After running those 3 commands, I am getting compilation errors after starting the server:

```
WARNING in ./node_modules/pikaday/pikaday.js 28:17-24
Critical dependency: the request of a dependency is an expression
 @ ./app/javascript/legacy/campaigns/new/wizard.js
 @ ./app/javascript/legacy/campaigns/peer_to_peer/page.js
 @ ./app/javascript/packs/page__campaigns__peer_to_peer.js

WARNING in ./node_modules/pikaday-time/pikaday.js 28:17-24
Critical dependency: the request of a dependency is an expression
 @ ./app/javascript/legacy/common/pikaday-timepicker.js
 @ ./app/javascript/legacy/campaigns/new/wizard.js
 @ ./app/javascript/legacy/campaigns/peer_to_peer/page.js
 @ ./app/javascript/packs/page__campaigns__peer_to_peer.js

ERROR in ./app/javascript/page_info.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (.../houdini/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
 @ ./app/javascript/legacy_react/api/api/NonprofitsApi.ts 22:16-52
 @ ./app/javascript/legacy_react/api/api/api.ts
 @ ./app/javascript/legacy_react/api/index.ts
 @ ./app/javascript/legacy_react/src/components/common/Root.tsx
 @ ./app/javascript/legacy_react/app/create_new_offsite_payment_pane.tsx
 @ ./app/javascript/packs/create_new_offsite_payment_pane.js
```
I wish I'm a bit more handy with Rails to debug this further, but if you can add a blurb or to in README to describe the structure of the system and/or the framework(s) used, I can look into such things a bit more.

**Comment by wwahammy** [comment]
Hey there @stevel408. Thanks for the patience. I've noticed a few things that MIGHT be causing the issue you're currently having and I've made patches.

If you're still able, could you update to the latest version and try again?

Also, I really do need to summarize the structure, I hope I can get to that in the next week or so. The work of a FOSS developer is never done :smile:

**Comment by stevel408** [comment]
I think the situation is the same, the first error looks like:

```
WARNING in ./node_modules/pikaday/pikaday.js 28:17-24
Critical dependency: the request of a dependency is an expression
 @ ./app/javascript/legacy/campaigns/new/wizard.js
 @ ./app/javascript/legacy/campaigns/peer_to_peer/page.js
 @ ./app/javascript/packs/page__campaigns__peer_to_peer.js

WARNING in ./node_modules/pikaday-time/pikaday.js 28:17-24
Critical dependency: the request of a dependency is an expression
 @ ./app/javascript/legacy/common/pikaday-timepicker.js
 @ ./app/javascript/legacy/campaigns/new/wizard.js
 @ ./app/javascript/legacy/campaigns/peer_to_peer/page.js
 @ ./app/javascript/packs/page__campaigns__peer_to_peer.js

ERROR in ./app/javascript/page_info.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (... .../houdini/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
 @ ./app/javascript/legacy_react/api/api/NonprofitsApi.ts 22:16-52
 @ ./app/javascript/legacy_react/api/api/api.ts
 @ ./app/javascript/legacy_react/api/index.ts
 @ ./app/javascript/legacy_react/src/components/common/Root.tsx
 @ ./app/javascript/legacy_react/app/create_new_offsite_payment_pane.tsx
 @ ./app/javascript/packs/create_new_offsite_payment_pane.js


FATAL: Listen error: unable to monitor directories for changes.
Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.
```

The code I used was:

```
$ git log -1
commit 858860f274b68c4b1dd593ab2604b918c24ae396 (HEAD -> main, origin/main)
Author: Eric <eric@commitchange.com>
Date:   Thu Jun 18 17:15:38 2020 -0500

    Fix bug in concern where the wrong Nonprofit class was being searched for
```

**Comment by wwahammy** [comment]
@stevel408 just an update, I haven't forgotten about you! I'm installed an instance of Ubuntu 18.04 in a virtual machine. Hopefully I can replicate the bug.

**Comment by wwahammy** [comment]
@stevel408 I might have stumbled on something. How much memory do you have on your computer?

**Comment by stevel408** [comment]
I think I should have plenty (4G):

```
$ free
              total        used        free      shared  buff/cache   available
Mem:        4039512      934392     1073672       20080     2031448     2797452
Swap:        999420        1548      997872
```
If you suspect it's an issue with the OS, I'm happy to get onto 20.04 myself as well.

**Comment by wwahammy** [comment]
4G should be plenty for the build. I can create the bug on 2Gbs on 18.04 in
a VM but it only seemed to happen if I randomly chose to cancel the build
partway through. Unfortunately, I'm still not sure what the exact
conditions are.

One more thing we can try is to run `bin/rails assets:clobber`. This
deletes any cached or compiled Javascript; it's possible something there
from a previous build is causing this. After you do that, start the server
again using `bin/rails server` and give it a try.

**Comment by stevel408** [comment]
Still the same problem and same symptom.

I wonder though, can this perhaps be added to the test cases? so that if the test passes, we should not have this problem. That way, it's a bit easier to debug the problem. 

Also, like I mentioned before, I think the project holds a great deal of potential, and I'll start to figure out how a standard rails project is structured, and who knows maybe able to figure this out myself...

**Comment by wwahammy** [comment]
> Still the same problem and same symptom.
Hmmm, alright, let's try one last thing. If you run `bin/rails assets:precompile`, it should compile the javascript. Once that completes, you should be able to go to `bin/rails server` and it won't try to compile the javascript on page load. That might get around it. (although I'm mostly guessing at this point).

> I wonder though, can this perhaps be added to the test cases? so that if the test passes, we should not have this problem. That way, it's a bit easier to debug the problem.
I absolutely would love a test case for this once we figure out what in the world is going on. :smile:

> Also, like I mentioned before, I think the project holds a great deal of potential, and I'll start to figure out how a standard rails project is structured, and who knows maybe able to figure this out myself...
Feel free to ask me on Zulip about any questions you may have. You questions might help us figure out what documentation is needed for those interested in Houdini who are new to Rails.

We use a partially modified Rails setup but it's gotten a lot closer to standard Rails with less customization over time so standard Rails documentation is relatively helpful to get up to speed.

**Comment by stevel408** [comment]
OK, the precompiling got rid of the errors on the server side command line. But the browser side still doesn't work, it reports the following JavaScript error:

```
Error: Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (.../houdini/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

As a Rails outsider, I can see that precompile seems to assemble the assets (CSS, etc.), but there's something at run time at the JavaScript level that needs to be "built", I mean, for whatever it's worth.

**Comment by wwahammy** [comment]
Hmm, this is really weird.

rails-erb-loader is a tool for generating some javascript based on
information in the database before it gets compiled. I figured the
precompile might work around that and it should have.

Would you be open to doing a screenshare? I think it'd be helpful if I
could see what you're seeing and we can debug this together. I'm honestly
really stumped. I want to get to the bottom of this

Also, thank you so much for your patience, I can imagine how frustrating
this is to you.

**Comment by wwahammy** [comment]
I think this is cleared up, so I'm going to close. Feel free to reopen @stevel408 if the settings page throws an exception again.

**Comment by stevel408** [comment]
Sounds great, thank you Eric!
