### ISSUE TITLE
[BUG] NPM dependency `validator` uses an offensive term as part of its API

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#354]
## Description
`validator`, an NPM package for string validation and coercion, uses an offensive term as part of its API, namely "blacklist".
I've replaced every usage of that term with "blocklist" in #353 but it's functionally impossible to replace that term when importing that functionality:

[`import blocklist from "validator/lib/blacklist";`](https://github.com/houdiniproject/houdini/blob/35402a0d182b508410793a586c1900cb687edbc1/app/javascript/legacy_react/src/components/create_offsite_payment_pane/CreateOffsitePaymentPane.tsx#L21)

## Possible Fix
We could vendor the function or write our own. We could also see if a package we're already using has an identical function. The two use-cases use legacy tech so we might want to just wait to replace those if we don't use validator in many other places.

**Comment by faco400** [comment]
Hello @wwahammy, me, @Rafaelltm and @Carlacangussu are students from University of Brasilia. We would like to start contributing to the houdini project and help the community. We want to take this issue as a start to our contribution.

**Comment by wwahammy** [comment]
Hi @faco400, @rafaelltm and @carlacarngussu! Thanks for taking on this task. I'm not sure how difficult this is going to be. I would recommend investigating how validator is currently used and document it here. That may help inform you and the rest of the community on what needs to be done.

**Comment by faco400** [comment]
So, me @Rafaelltm  and @Carlacangussu did some research on what the validator module does and apparently it is used to validate strings (Check if string is email, see if string matches certains chars and so on...) And also to sanitize strings (remove certain elements from strings). If we are correct, the houdini project is using only the "blacklist" method from this module, which sanitizes the string removing regex elements. It is being used specifically to remove the '$,' from a dollarString, both in the files: app/javascript/legacy_react/src/components/create_offsite_payment_pane/CreateOffsitePaymentPane.tsx app/javascript/legacy_react/src/components/edit_payment_pane/EditPaymentPane.tsx

You can see them in the method loadFormFromData() present in both files being used like this:
`output: (dollarString: string) => parseFloat(blocklist(dollarString, '$,'))`

**Comment by wwahammy** [comment]
That is accurate!
