### ISSUE TITLE
[FEATURE] Migrate Sign In Page to best-practices React and Material-UI

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#363]
**Describe the solution you'd like**
The old Sign In needs to be rewritten in Material UI using proper React design. This work will be completed by the interns hired by CommitChange. The work will be done in the [feature/sign_in-to-mui](https://github.com/houdiniproject/houdini/tree/feature/sign_in-to-mui) branch.

A specification is included below

# sign_in Specification

The `users/sign_in` page is the login page for users of Houdini. This page should consist of two major components.

* `SignInPage`
* `SignInComponent`

## Characteristics of all components in specification

* MUST be written to use React hooks and be a React function component.
* MUST be keyboard accessible (implied by the next item but just to be clear)
* MUST be WCAG 2.1, level AA compatible or close. The best tool I've found for finding these bugs is The AXE Beta tool. It [requires registration](https://www.deque.com/axe/beta/) and installation of the extension in Chrome/Chromium. Another good approximation for testing this is going to the Firefox Development Tools, going to `Check for Issues` and selecting `All Issues`. Other tools to assist are the [non-beta Axe Browser Extension](https://www.deque.com/axe/browser-extensions/) and [the Wave Browser Extension](https://wave.webaim.org/extension/). This is admittedly a big task to be perfect so let's try our best.
* MUST use text from the current locale
* MUST use Material-UI components as much as possible.
* MUST use the current theme for styling.

## `SignInPage`

`SignInPage` consists of almost the entire sign_in page. It must be a responsive component. If you look at `/users/sign_in`, that will show what is being replaced with `SignInPage`.

![Current User Sign In Form](https://user-images.githubusercontent.com/94169/96768180-29fd5f80-13a3-11eb-9b80-cd569a36c162.png)

### `SignInPage` Input

`SignInPage` will have the following parameters and/or context (details to be added) available to it.

* `redirectUrl` - the url to redirect to after a successful sign in, passed in as a parameter.
* `currentUser` - object describing the current user. Available via the `useCurrentUser` hook
* `new_user_password_path` - available via the `routes` module in the `app/javascript` directory
* `static_terms_and_privacy_path` - available via the `routes` module in the `app/javascript` directory
* `legalName` - the legal name of the Houdini hoster. Available via the `useHoster` hook
* the Intl object - `useIntl` which allows you to get the current locale, get text for the current locale, etc.

### `SignInPage` Characteristics

The `SignInPage` has three major states: `ready`, `submitting`, `success`. Important characteristics:

* MUST start in the `ready` state
* MUST only allow interaction with page elements when in the `ready` state.
* MUST move to the `success` state when the child SignInComponent fires `onSuccess`
* MUST move to the `ready` state when the child SignInComponent fires `onFailure`
* MUST redirect to `redirectUrl` when in the `success` state
* MUST move to the `submitting` state if the form is being submitted if `submitting` is true
* MUST display the `SignInComponent` as a child
	* To be decided: it's possible the `SignInComponent` could be hidden on `submitting` and/or `success`. The design process will
	figure this out.
* MUST have a way for a user to get to the forgot password page
* MUST have a design for a Houdini hoster to add additional links to the `SignInPage`, such as for user registration, nonprofit sign up, etc. Don't worry about the method we use to get the links, just make sure the design considers this and the mechanism is documented.
* MUST have an indicator to the user of when `submitting` or `success`.
	* To be decided: Whether to use the same or different indicators for  `submitting` and `success`
* MUST include a copyright statement of Copyright legalName of hoster
* MUST include a link to the Terms and Privacy
* MUST have a design where a Houdini instance owner can add additional links along with the terms and privacy link. Don't worry about the method we use to get the links, just make sure the design considers this and is documented.
* MUST be clear to the user why they're there and what to do.
* MUST have an ErrorBoundary to catch all rendering errors and have fallback with the properties FallbackComponent OR FallbackRender set.
* MUST have a place designated for adding a logo (look at the Houdini Project logo above)

## `SignInComponent`

The `SignInComponent` provides the core functionality for handling user sign in. It should be a responsive component. Generally consists of a fields for email and password and a method of submission (probably a button). A subset of functionality on the `/users/sign_in` page would be replaced with `SignInComponent` as shown in the following screenshot:

![Current form fields which will be replaced by SignInComponent](https://user-images.githubusercontent.com/94169/96768450-7f397100-13a3-11eb-9a73-79e8eefb3eaa.png)

### `SignInComponent` Input

The `SignInComponent` has the following parameters and/or context (details to be added) available to it:

* `signedIn` - boolean describing whether the user is currently signed in, Available via the `useCurrentUserAuth` hook
* `lastError` - a `SignInError` object or falsy. Available via the `useCurrentUserAuth` hook
* `onSuccess` - an optional function passed in that is called when moving to the `success` state. Provide an empty function via the component's defaultProps.
* `onSubmitting` - an optional function passed in that is called when the moved to the `submitting` state. Provide an empty function via the component's defaultProps.
* `onFailure` - an optional function passed in that is called when when moving back to the `ready` state from the `submitting` state. Provide an empty function via the component's defaultProps.
* the Intl object - `useIntl` which allows you to get the current locale, get text for the current locale, etc.

### `SignInComponent` Characteristics

The `SignInComponent` has the following states: `ready`, `canSubmit`, `submitting`, `success`

* MUST start in the `ready` state
* MUST move to the `success` state when `signedIn` from `useCurrentUserAuth` is true
* MUST have a way to enter email and password. (probably two fields visible at the same time but other options are possible) when in the `ready` state.
* MUST do clientside validation on whether the email and password meet our requirements
	* MUST set error messages if they don't
	* MUST mark the relevant fields as in error if they don't
	* MUST not mark the fields in error or show error messages if the user hasn't touched the field
	* If clientside validation passes, MUST move into the `canSubmit` state
* MUST NOT allow submission if `SignInComponent` isn't in the `canSubmit` state.
* MUST move into the `submitting` state when the form submission is started
* MUST remove any displayed "server errors" if in the `submitting` state
* MUST indicate that a submission is happening when in the `submitting` state
* If a submission fails:
	* MUST move into the `ready` or `canSubmit` state as the clientside validation allows (usually `canSubmit`)
	* MUST display any errors received from `lastError` to the user
* If a submission succeeds:
	* MUST move into the `success` state
* MUST use Formik for managing the form, its state and the state of input fields.

**Comment by tttp** [comment]
@wwahammy could you attach a screen shot of the sign it page and/or a link to the existing one?

On my [react project](https://proca.foundation) we use [React hook form](https://react-hook-form.com/) and I recommend using it. It takes care of some of the state management out of the box (ready/submit/validation...)

**Comment by wwahammy** [comment]
> @wwahammy could you attach a screen shot of the sign it page and/or a link to the existing one?

Thank you for mentioning that! I intended to but forgot to. I'll do that when I get to the office and hour or so.

> On my [react project](https://proca.foundation) we use [React hook form](https://react-hook-form.com/) and I recommend using it. It takes care of some of the state management out of the box (ready/submit/validation...)

React hook form seems like a good tool but I'd prefer to stick to Formik unless there's a good reason not to. We're already using Formik and it's recommended in the [React docs](https://reactjs.org/docs/forms.html). That said they don't work that differently so if we decide to switch it likely wouldn't require huge amount of rearchitecture, just time.

**Comment by wwahammy** [comment]
Screenshots added.

**Comment by wwahammy** [comment]
@lbruesehoff and @Gintorres: I modified the document slightly, I realized that we need a place to put a logo or site name in the SignInPage design.
