### ISSUE TITLE
[BUG] Nonprofit URL validation

### ISSUE THREAD

**Issue by clarissalimab** [houdiniproject/houdini#457]
## Description
On the nonprofit register screen, starting from the onboard, the user is being required to type the "https://www." prefix on the URL field.

## Expected Behavior
It should not be mandatory to write the "https://www." prefix on the URL field for the nonprofit registering, or, at least, the user should receive meaningful feedback that they must fill the field with the prefix.

## Actual Behavior
The user can't register the nonprofit if they fill the URL field only with the "example.com" data, but the user account gets registered. The user also does not get any feedback about what happened.

## Possible Fix
Update the validation to require the "https://www." URL prefix or remove that requirement from the backend.

## Steps to Reproduce

1. Set up the environment for the first time;
2. Run the server and navigate to `localhost:5000/onboard`;
3. Fill the registration form. On the URL field for the nonprofit, fill in with a website that does not contain the "https://www." prefix.

## Context
I was registering for the first time in my development environment.

## Your Environment

* Ruby version: ruby 2.6.6
* Operating System and version: Arch (kernel 5.9.14-arch1-1)

**Comment by wwahammy** [comment]
@tony-gutierrez this is definitely a related issue. I have the hunch is at https://github.com/houdiniproject/houdini/blob/main/lib/nonprofit_creation.rb#L17. If you move that line inside the ActiveRecord::Base.transaction block, does that correct this bug?
