### ISSUE TITLE
[BUG] Exclusionary term related to Custom Fields

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#460]
Currently Houdini includes the term CustomFieldMaster in the source code. Master is an offensive term and should be removed from Houdini. The Houdini project community apologizes for its legacy use.

Similar to the work on #456, changes which need to be made include:

* renaming the `CustomFieldMaster` class to `CustomFieldDefinition`
* renaming the `custom_field_masters` database table
* renaming the `CustomFieldMasterController` class and  any routes referring to it.
* finding any place where the `custom_field_masters` table is used in the source code and rename it to `custom_field_definitions`

There may be other legacy uses which must be evaluated and found.

**Comment by heronsousa** [comment]
I'm working on it!
