### ISSUE TITLE
Update off of Ruby 2.3 (and update to Rails)

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#47]
Currently, Houdini uses Ruby 2.3 and the latest version of Rails 3.2. Ruby 2.3 is in security maintenance mode and will [stop receiving security updates near the end of March, 2019](https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/). Accordingly we need to upgrade to Ruby 2.4 or higher. Additionally, as Rails 3.2 is not supported on Ruby 2.4 or higher, we need to update to at least Rails 4.2.

**Comment by ericschultz** [comment]
I propose we do this for version 2 which will need to be released in Q1 of 2019

**Comment by phongtruongg** [comment]
I plan to use Houdini for my project, I think I can help you upgrade to Rails 6

**Comment by wwahammy** [comment]
@phongtruongg that's great! I have a partial Rails 5 upgrade done already at https://github.com/houdiniproject/houdini/tree/rails_v5. I'd love to coordinate with you on upgrade work. Would you be interested in meeting on our Zulip in the coming week?
