### ISSUE TITLE
[FEATURE] Use rubocop!

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#488]
Currently the project has a less than consistent format for ruby source code. This is not easy to work with. Adding a rubocop format that is part of a build would help. This addition of rubocop must meet the following standards:

* must exclude files which currently are in the codebase. We don't want to do a huge reformat and blow our history to bits. As files have significant rewrites, we can consider adding them to the format requirements.
* must use the tab for tabs. This is an accessibility feature as spaces are less accessible for screenreaders.
* must be included in the build process, i.e. if code doesn't meet the standard, the build should fail.

It also should:

* be somewhat close to one of the formats we use. (and, holy cow, are there a lot of them)
* be automagically sensed by editors like VSCode. If that requires an extension, that extension should be documented if possible.

**Comment by clarissalimab** [comment]
I also thought about using a CodeSmell tool, like [reek](https://github.com/troessner/reek). What do you think?

**Comment by wwahammy** [comment]
I'm not familiar with reek but it sounds like it could be useful!
