### ISSUE TITLE
[FEATURE] use erb-lint

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#510]
There's an linter for erb files called [erb-lint](https://github.com/Shopify/erb-lint). We may want to consider using it.

**Comment by luisgfmarques** [comment]
Hello, I and @victorhugo21 are Software Engineering students in Brasil and we are exciting in start contributing with Houdini, we want start work in this issue :)

**Comment by wwahammy** [comment]
@luisgfmarques and @victorhugo21: Sounds great!

**Comment by victorhugo21** [comment]
Hi @wwahammy, I and @luisgfmarques have something to ask about this issue. If only add the erb-lint and run with the autocorrect option its good or we have also to resolve every error found and not autocorrected?

**Comment by wwahammy** [comment]
I'd recommend handling this in a three steps:

1. Send a PR after adding erb-lint and making sure it's runnable with instructions for how to run it. Don't correct anything in this PR.
2. After that's approved, create a new issue where you begin to run it and report back on what results we get. We'll discuss those results and we can decide what needs to be changed, what checks should have exceptions, etc.. Then create a PR where you begin fixing the errors, adding any exceptions needed to the checks, etc. We'll continue discussing changes until we're satisfied with the results.
3. Lastly, after that PR is merged, you can add erb-lint to our Github action workflows to check new PRs. If erb-lint fails on the check, then the workflow would fail. This guarantees that we keep the erb files in the project in a clean state going forward.

Sound good?
