### ISSUE TITLE
[BUG] The nonprofit creation allows you to create it with a state that is not in the US

### ISSUE THREAD

**Issue by clarissalimab** [houdiniproject/houdini#586]
## Description

When using the nonprofit creation command (`bin/rails houdini:nonprofit:create`), I was allowed to create it with a state that is not from the US, but when I navigated to its dashboard, I had an error:

![image](https://user-images.githubusercontent.com/15739610/117025635-7706aa80-acd1-11eb-861d-d34641322407.png)

## Expected Behavior

A validation error should come up if the user tries to create a nonprofit that is not from the US.

## Steps to Reproduce

1. Start the project from scratch;
2. Create the first nonprofit by running `bin/rails houdini:nonprofit:create` with the following options:
```sh
What is the nonprofit's name? Dognity
What is the nonprofit's state? DF
What is the nonprofit's city? Brasília
[OPTIONAL] What is the nonprofit's public website? 
[OPTIONAL] What is the nonprofit's public e-mail? 
[OPTIONAL] What is your nonprofit's public phone number? 
What is your nonprofit's admin's name? Clarissa
What is your nonprofit's admin's email address? (It'll be used for logging in) clarissa@commitchange.com
What is the nonprofit's admin's password?
```
3. Start the server, navigate to `localhost:5000` and log in;
4. You should see the error instead of the dashboard.

**Comment by clarissalimab** [comment]
I realized that this problem happens because I was registering my nonprofit with a state that is not on the US. My suggestion would be to validate that on the Nonprofit creation.

**Comment by thiagolopess** [comment]
Me, @igor-paiva and @marcelog5 are working on it!
