### ISSUE TITLE
[FEATURE] Change to using strict Typescript

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#661]
**Is your feature request related to a problem? Please describe.**
Typescript has valuable typechecks through it's [strict mode](https://www.typescriptlang.org/tsconfig#strict) that we're not using because we don't have strict mode on. Using `strict` for typescript may also allow usage of the strict Javascript mode which has increased performance in browser.

**Describe the solution you'd like**
* Add `strict: true` to `tsconfig.json`
* Fix all of the strict errors. Most of them should be straightforward.

**Comment by GuilhermeBraz** [comment]
Hey @wwahammy, me and @JoaoVitorFarias are from University of Brasilia. We're excited to start contributing to the houdini project and be of help to the houdini community. It will be our first contribution!
