### ISSUE TITLE
[BUG] Unable to create a campaign

### ISSUE THREAD

**Issue by mikhaun** [houdiniproject/houdini#767]
Trying to create a campaign results in an error

## Description

Whenever I try to create a campaign, I get an error message notifying of a undefined method on a nil class. 
I have not made any modifications to the source code. This issue occurs in every environment tested. 

![houdini_create_campaign_error](https://user-images.githubusercontent.com/85194502/134565853-2e182614-ec95-4d66-844d-aea80cab41ed.PNG)

## Possible Fix

lib/create/create_campaign.rb expects params containing a campaign object. It is currently invoked with params that do not contain the campaign object.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Ruby version:
* Server type and version:
* Operating System and version: Ubuntu  20.04
* Link to your project:

**Comment by wwahammy** [comment]
@mikhaun: I've proposed a PR at #774 that should address this bug and likely the other you saw. We should merge it sometime today.
