### ISSUE TITLE
[BUG] Updating campaign causes server to crash

### ISSUE THREAD

**Issue by mikhaun** [houdiniproject/houdini#778]
Trying to update a campaign through the UI results in a "Stack level too deep" loop causing the server to crash.

## Description

Trying to update a campaign results in a "Stack level too deep" loop causing the server to crash. 
The campaign object does get updated, however the server must be restarted to recover from the crash. 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Ruby version:
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by wwahammy** [comment]
@mikhaun thanks for the report! I am fixing this right now. I might not have it until tomorrow though.

**Comment by wwahammy** [comment]
@mikhaun Here's a PR with this fix which I hope to have merged today https://github.com/houdiniproject/houdini/pull/780

**Comment by wwahammy** [comment]
@mikhaun this fix is merged into `main`. Thanks for your patience!
