### ISSUE TITLE
[BUG] Unable to create peer to peer campaigns

### ISSUE THREAD

**Issue by mikhaun** [houdiniproject/houdini#779]
When creating a peer to peer campaign through the peer-to-peer wizard nothing happens.  The wizard always prompts to sign up or login regardless of current login status. There is no option to continue from this page to create the peer-to-peer campaign. 

## Description

![image](https://user-images.githubusercontent.com/85194502/135354780-5cee5e0c-9d9d-4634-b4b7-3f4fd071143b.png)

Trying to sign up results in a new user account being created. However this does not change anything on the page. And the user is not notified of the successful signup, though it is reflected in Users table.
If I choose to login with an existing account, the user is logged in but nothing on the page changes. No new options are presented. 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Ruby version:
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by wwahammy** [comment]
Thanks for the report @mikhaun! Could you check your browsers javascript console when you're at that page (Usually can get to it by pressing `Ctrl-Shift-I`) and copy and error messages you go in it? I suspect I know the problem but this would speed up the process.

**Comment by wwahammy** [comment]
@mikhaun I actually debugged this and I think I have a fix at https://github.com/houdiniproject/houdini/pull/781

**Comment by wwahammy** [comment]
@mikhaun I've now merged a fix for this. Thanks for the patience!
