### ISSUE TITLE
[FEATURE] Meaningful methods names

### ISSUE THREAD

**Issue by heronsousa** [houdiniproject/houdini#783]
**Is your feature request related to a problem? Please describe.**
I came across some methods that I didn't understand their purpose until I read their implementation

**Describe the solution you'd like**
I thought of some alternatives and I would like to know what you think:
[`simple_date`](https://github.com/houdiniproject/houdini/blob/40debec3d8dab0dff27ca3c9d1b2a87350ca922d/app/helpers/application_helper.rb#L31) -> `format_date_to_mdY`
[`readable_date`](https://github.com/houdiniproject/houdini/blob/40debec3d8dab0dff27ca3c9d1b2a87350ca922d/app/helpers/application_helper.rb#L45) -> `format_date_with_month_name`

And some others. If you think that it can be implemented, I can work on that and any other problem related to this.

**Comment by wwahammy** [comment]
@heronsousa I like this idea!

Could you list all of the methods that you're thinking of and where they are in the repo?

**Comment by heronsousa** [comment]
For a while, I started by mapping the helpers folder and i have these:

[`simple_date`](https://github.com/houdiniproject/houdini/blob/40debec3d8dab0dff27ca3c9d1b2a87350ca922d/app/helpers/application_helper.rb#L31) -> `format_date_to_mdY`
[`readable_date`](https://github.com/houdiniproject/houdini/blob/40debec3d8dab0dff27ca3c9d1b2a87350ca922d/app/helpers/application_helper.rb#L45) -> `format_date_with_month_name`
[`url_with_param`](https://github.com/houdiniproject/houdini/blob/40debec3d8dab0dff27ca3c9d1b2a87350ca922d/app/helpers/application_helper.rb#L59) -> `append_param_to_url`
[`date_and_time`](https://github.com/houdiniproject/houdini/blob/40debec3d8dab0dff27ca3c9d1b2a87350ca922d/app/helpers/application_helper.rb#L49) -> `format_date_to_datetime_timezone`
[`simple_time`](https://github.com/houdiniproject/houdini/blob/40debec3d8dab0dff27ca3c9d1b2a87350ca922d/app/helpers/application_helper.rb#L38) -> `format_time_to_lMP`

The actual method name has the link where it is located

**Comment by wwahammy** [comment]
I like this! The only one that I'm a little unsure in is format_time_to_lMP. What does that stands for?

**Comment by heronsousa** [comment]
lMP is the time format. I confess that I'm not sure about this one. I'm going to work out some kind of alternative.

**Comment by wwahammy** [comment]
@heronsousa ah, looking at it, I get what you mean. Let's go with a different name for that one because it's not clear immediately what it means.

If a new name isn't immediately forthcoming, you could make progress and fix the other ones to close this issue and move the `simple_time` rename to a new issue?

**Comment by heronsousa** [comment]
Ok. We can make that! If I have any idea, I will let you know.

**Comment by WeillerFernandes** [comment]
Hey @wwahammy, me and @GuilhermeBraz are from University of Brasilia. We're excited to start contributing to the houdini project and be of help to the houdini community. We believe this is a good issue to start.

**Comment by wwahammy** [comment]
Thanks @WeillerFernandes  and @GuilehermeBraz! And welcome to Houdini!
