### ISSUE TITLE
[FEATURE] Old code comments

### ISSUE THREAD

**Issue by marcelog5** [houdiniproject/houdini#789]
**Is your feature request related to a problem? Please describe.**
To respect clean code is advised to remove old code commented.

**Describe the solution you'd like**
Just remove the commented code.

**Additional context**
For example have a commented code in models/base.rb

**Comment by marcelog5** [comment]
If this make sense I will work on this commented codes and see if this happen in other places on the project

**Comment by wwahammy** [comment]
@marcelog5 Good idea!

**Comment by marcelog5** [comment]
Hi @wwahammy , do you know what this line of code mean or do:
![Img](https://user-images.githubusercontent.com/48961541/136212282-6d4d774d-cdca-46bc-93e1-d1b575d9c04d.png)

this code is in app/controllers/nonprofits/donations_controller

**Comment by marcelog5** [comment]
Hi @wwahammy , this piece of code commented:

![Img](https://user-images.githubusercontent.com/48961541/136220384-d7658ed1-91cc-4da3-9b57-df0150fb93d5.png)

I can consider a old code comment or this is necessary to a better understanding of the code?

this code is in app/models/campaing_gift_option

**Comment by wwahammy** [comment]
@marcelog5 the comments at the beginning of some of the `app/models` files are probably redundant but let's keep them.

**Comment by wwahammy** [comment]
In `app/controllers/nonprofits/donations_controller` you can remove that pointless comment but keep the `private`
