### ISSUE TITLE
Space in between currency symbol and number

### ISSUE THREAD

**Issue by ericschultz** [houdiniproject/houdini#84]
Looking at `print_currency`, the unit used for [`number_to_currency` on line 17](https://github.com/houdiniproject/houdini/blob/master/app/helpers/application_helper.rb#L19) has a trailing space. This creates strings such as "$ 9" (space in-between). As this doesn't look very good, I'd like to remove the trailing space on unit. What I don't understand though is what it's there for.

@tttp on [November 3rd in the CommitChange repo](https://github.com/CommitChange/commitchange.com/commits/master/app/helpers/application_helper.rb) (note: this is a private repo). Do you know why you had the trailing space in there @tttp?

**Comment by tttp** [comment]
Hi,

Actually, what we would need is to change the order so the symbol is after, eg. 42€ vs $42, I don't recall why the space was added, might just be my french roots (we love to put space here and there) ;O
