### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by ajit-fawade** [houdiniproject/houdini#94]
Here is the log after running docker-compose up

➜  houdini git:(master) ✗ docker-compose up
houdini_memcached_1 is up-to-date
houdini_db_1 is up-to-date
Starting houdini_web_1 ... done
Attaching to houdini_memcached_1, houdini_db_1, houdini_web_1
memcached_1  | Signal handled: Terminated.
memcached_1  | Signal handled: Terminated.
db_1         | LOG:  database system was shut down at 2018-09-06 05:26:09 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  autovacuum launcher started
db_1         | LOG:  received smart shutdown request
db_1         | LOG:  autovacuum launcher shutting down
db_1         | LOG:  shutting down
db_1         | LOG:  database system is shut down
db_1         | LOG:  database system was shut down at 2018-09-06 05:27:21 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  autovacuum launcher started
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  received smart shutdown request
db_1         | LOG:  autovacuum launcher shutting down
db_1         | LOG:  shutting down
db_1         | LOG:  database system is shut down
db_1         | LOG:  database system was shut down at 2018-09-06 05:45:26 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  autovacuum launcher started
web_1        | 10:48:10 web.1    | started with pid 10
web_1        | 10:48:10 worker.1 | started with pid 11
web_1        | 10:48:12 web.1    | [10] Puma starting in cluster mode...
web_1        | 10:48:12 web.1    | [10] * Version 3.11.2 (ruby 2.3.7-p456), codename: Love Song
web_1        | 10:48:12 web.1    | [10] * Min threads: 1, max threads: 1
web_1        | 10:48:12 web.1    | [10] * Environment: development
web_1        | 10:48:12 web.1    | [10] * Process workers: 1
web_1        | 10:48:12 web.1    | [10] * Preloading application
web_1        | 10:48:12 worker.1 | rake aborted!
web_1        | 10:48:12 web.1    | [10] ! Unable to load application: Errno::EACCES: Permission denied @ dir_s_mkdir - /myapp/tmp
web_1        | 10:48:12 worker.1 | Errno::EACCES: Permission denied @ dir_s_mkdir - /myapp/tmp
web_1        | 10:48:12 web.1    | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:73:in `dump_data'
web_1        | 10:48:12 web.1    | Errno::EACCES: Permission denied @ dir_s_mkdir - /myapp/tmp
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:55:in `commit_transaction'
web_1        | 10:48:12 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:47:in `transaction'
web_1        | 10:48:12 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:254:in `fu_mkdir'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:138:in `push_paths_locked'
web_1        | 10:48:12 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:121:in `block in reinitialize'
web_1        | 10:48:12 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:226:in `reverse_each'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:115:in `synchronize'
web_1        | 10:48:12 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:226:in `block in mkdir_p'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:115:in `reinitialize'
web_1        | 10:48:12 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:211:in `each'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:14:in `initialize'
web_1        | 10:48:12 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache.rb:29:in `new'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:73:in `dump_data'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache.rb:29:in `setup'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:55:in `commit_transaction'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap.rb:24:in `setup'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:47:in `transaction'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/setup.rb:33:in `<top (required)>'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:138:in `push_paths_locked'
web_1        | 10:48:12 worker.1 | /myapp/config/boot.rb:8:in `require'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:121:in `block in reinitialize'
web_1        | 10:48:12 worker.1 | /myapp/config/boot.rb:8:in `<top (required)>'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:115:in `synchronize'
web_1        | 10:48:12 worker.1 | /myapp/config/application.rb:2:in `require'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:115:in `reinitialize'
web_1        | 10:48:12 worker.1 | /myapp/config/application.rb:2:in `<top (required)>'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:14:in `initialize'
web_1        | 10:48:12 worker.1 | /myapp/Rakefile:5:in `require'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache.rb:29:in `new'
web_1        | 10:48:12 worker.1 | /myapp/Rakefile:5:in `<top (required)>'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache.rb:29:in `setup'
web_1        | 10:48:12 worker.1 | /usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap.rb:24:in `setup'
web_1        | 10:48:12 worker.1 | /usr/local/bin/bundle:23:in `load'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/setup.rb:33:in `<top (required)>'
web_1        | 10:48:12 worker.1 | /usr/local/bin/bundle:23:in `<main>'
web_1        | 10:48:12 web.1    |   /myapp/config/boot.rb:8:in `require'
web_1        | 10:48:12 worker.1 | (See full trace by running task with --trace)
web_1        | 10:48:12 web.1    |   /myapp/config/boot.rb:8:in `<top (required)>'
web_1        | 10:48:12 web.1    |   /myapp/config/application.rb:2:in `require'
web_1        | 10:48:12 web.1    |   /myapp/config/application.rb:2:in `<top (required)>'
web_1        | 10:48:12 web.1    |   /myapp/config/environment.rb:3:in `require'
web_1        | 10:48:12 web.1    |   /myapp/config/environment.rb:3:in `<top (required)>'
web_1        | 10:48:12 web.1    |   config.ru:3:in `require'
web_1        | 10:48:12 web.1    |   config.ru:3:in `block in <main>'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
web_1        | 10:48:12 web.1    |   config.ru:in `new'
web_1        | 10:48:12 web.1    |   config.ru:in `<main>'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/configuration.rb:318:in `load_rackup'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/configuration.rb:243:in `app'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/runner.rb:138:in `load_and_bind'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/cluster.rb:397:in `run'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/launcher.rb:183:in `run'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/cli.rb:77:in `run'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/gems/puma-3.11.2/bin/puma:10:in `<top (required)>'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/bin/puma:23:in `load'
web_1        | 10:48:12 web.1    |   /usr/local/bundle/bin/puma:23:in `<top (required)>'
web_1        | 10:48:13 web.1    | exited with code 1
web_1        | 10:48:13 system   | sending SIGTERM to all processes
web_1        | 10:48:13 worker.1 | exited with code 1
houdini_web_1 exited with code 1

**Comment by ericschultz** [comment]
@ajit-fawade so I did a quick rewrite of our Docker for debugging setup. Right now the code is at https://github.com/houdiniproject/houdini/tree/docker-improvements and there are small changes to the instructions. Please check that version out and give it a try. Sorry about the annoyance and thanks for the patience.

**Comment by ajit-fawade** [comment]
@ericschultz  thanks a ton. I'll get back to you on this.

**Comment by ajit-fawade** [comment]
**### Still getting the same error:**
➜  debug git:(docker-improvements) docker-compose up
debug_db_1 is up-to-date
debug_memcached_1 is up-to-date
Creating debug_web_1 ... done
Attaching to debug_db_1, debug_memcached_1, debug_web_1
db_1         | The files belonging to this database system will be owned by user "postgres".
db_1         | This user must also own the server process.
db_1         | 
db_1         | The database cluster will be initialized with locale "en_US.utf8".
db_1         | The default database encoding has accordingly been set to "UTF8".
db_1         | The default text search configuration will be set to "english".
db_1         | 
db_1         | Data page checksums are disabled.
db_1         | 
db_1         | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1         | creating subdirectories ... ok
db_1         | selecting default max_connections ... 100
db_1         | selecting default shared_buffers ... 128MB
db_1         | selecting dynamic shared memory implementation ... posix
db_1         | creating configuration files ... ok
db_1         | running bootstrap script ... ok
db_1         | performing post-bootstrap initialization ... ok
db_1         | syncing data to disk ... ok
db_1         | 
db_1         | Success. You can now start the database server using:
db_1         | 
db_1         |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1         | 
db_1         | 
db_1         | WARNING: enabling "trust" authentication for local connections
db_1         | You can change this by editing pg_hba.conf or using the option -A, or
db_1         | --auth-local and --auth-host, the next time you run initdb.
db_1         | waiting for server to start....LOG:  database system was shut down at 2018-09-07 06:14:36 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  autovacuum launcher started
db_1         | LOG:  database system is ready to accept connections
db_1         |  done
db_1         | server started
db_1         | CREATE DATABASE
db_1         | 
db_1         | CREATE ROLE
db_1         | 
db_1         | 
db_1         | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1         | 
db_1         | LOG:  received fast shutdown request
db_1         | waiting for server to shut down...LOG:  aborting any active transactions
db_1         | .LOG:  autovacuum launcher shutting down
db_1         | LOG:  shutting down
db_1         | LOG:  database system is shut down
db_1         |  done
db_1         | server stopped
db_1         | 
db_1         | PostgreSQL init process complete; ready for start up.
db_1         | 
db_1         | LOG:  database system was shut down at 2018-09-07 06:14:38 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  autovacuum launcher started
db_1         | LOG:  database system is ready to accept connections
web_1        | 06:24:46 web.1    | started with pid 11
web_1        | 06:24:46 worker.1 | started with pid 12
web_1        | 06:24:47 web.1    | [11] Puma starting in cluster mode...
web_1        | 06:24:47 web.1    | [11] * Version 3.11.2 (ruby 2.3.7-p456), codename: Love Song
web_1        | 06:24:47 web.1    | [11] * Min threads: 1, max threads: 1
web_1        | 06:24:47 web.1    | [11] * Environment: development
web_1        | 06:24:47 web.1    | [11] * Process workers: 1
web_1        | 06:24:47 web.1    | [11] * Preloading application
web_1        | 06:24:47 worker.1 | rake aborted!
web_1        | 06:24:47 worker.1 | Errno::EACCES: Permission denied @ dir_s_mkdir - /myapp/tmp
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:73:in `dump_data'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:55:in `commit_transaction'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:47:in `transaction'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:138:in `push_paths_locked'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:121:in `block in reinitialize'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:115:in `synchronize'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:115:in `reinitialize'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:14:in `initialize'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache.rb:29:in `new'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache.rb:29:in `setup'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap.rb:24:in `setup'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/setup.rb:33:in `<top (required)>'
web_1        | 06:24:47 worker.1 | /myapp/config/boot.rb:8:in `require'
web_1        | 06:24:47 worker.1 | /myapp/config/boot.rb:8:in `<top (required)>'
web_1        | 06:24:47 worker.1 | /myapp/config/application.rb:2:in `require'
web_1        | 06:24:47 worker.1 | /myapp/config/application.rb:2:in `<top (required)>'
web_1        | 06:24:47 worker.1 | /myapp/Rakefile:5:in `require'
web_1        | 06:24:47 worker.1 | /myapp/Rakefile:5:in `<top (required)>'
web_1        | 06:24:47 worker.1 | /usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
web_1        | 06:24:47 worker.1 | /usr/local/bin/bundle:23:in `load'
web_1        | 06:24:47 worker.1 | /usr/local/bin/bundle:23:in `<main>'
web_1        | 06:24:47 worker.1 | (See full trace by running task with --trace)
web_1        | 06:24:47 web.1    | [11] ! Unable to load application: Errno::EACCES: Permission denied @ dir_s_mkdir - /myapp/tmp
web_1        | 06:24:47 web.1    | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
web_1        | 06:24:47 web.1    | Errno::EACCES: Permission denied @ dir_s_mkdir - /myapp/tmp
web_1        | 06:24:47 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir'
web_1        | 06:24:47 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:254:in `fu_mkdir'
web_1        | 06:24:47 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
web_1        | 06:24:47 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:226:in `reverse_each'
web_1        | 06:24:47 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:226:in `block in mkdir_p'
web_1        | 06:24:47 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:211:in `each'
web_1        | 06:24:47 web.1    |   /usr/local/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:73:in `dump_data'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:55:in `commit_transaction'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:47:in `transaction'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:138:in `push_paths_locked'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:121:in `block in reinitialize'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:115:in `synchronize'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:115:in `reinitialize'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:14:in `initialize'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache.rb:29:in `new'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache.rb:29:in `setup'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap.rb:24:in `setup'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/bootsnap-1.1.7/lib/bootsnap/setup.rb:33:in `<top (required)>'
web_1        | 06:24:47 web.1    |   /myapp/config/boot.rb:8:in `require'
web_1        | 06:24:47 web.1    |   /myapp/config/boot.rb:8:in `<top (required)>'
web_1        | 06:24:47 web.1    |   /myapp/config/application.rb:2:in `require'
web_1        | 06:24:47 web.1    |   /myapp/config/application.rb:2:in `<top (required)>'
web_1        | 06:24:47 web.1    |   /myapp/config/environment.rb:3:in `require'
web_1        | 06:24:47 web.1    |   /myapp/config/environment.rb:3:in `<top (required)>'
web_1        | 06:24:47 web.1    |   config.ru:3:in `require'
web_1        | 06:24:47 web.1    |   config.ru:3:in `block in <main>'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
web_1        | 06:24:47 web.1    |   config.ru:in `new'
web_1        | 06:24:47 web.1    |   config.ru:in `<main>'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/configuration.rb:318:in `load_rackup'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/configuration.rb:243:in `app'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/runner.rb:138:in `load_and_bind'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/cluster.rb:397:in `run'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/launcher.rb:183:in `run'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/puma-3.11.2/lib/puma/cli.rb:77:in `run'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/gems/puma-3.11.2/bin/puma:10:in `<top (required)>'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/bin/puma:23:in `load'
web_1        | 06:24:47 web.1    |   /usr/local/bundle/bin/puma:23:in `<top (required)>'
web_1        | 06:24:48 web.1    | exited with code 1
web_1        | 06:24:48 system   | sending SIGTERM to all processes
web_1        | 06:24:48 worker.1 | exited with code 1
debug_web_1 exited with code 1

**Comment by ericschultz** [comment]
Hmmm, very strange. This is after you ran `docker build` right?

While it's normal for `docker up` to fail on the first try (it's missing configuration that you'll add later in the process), it shouldn't be failing THAT way. :)

So a few things to consider/try:

* Clone the repo again into a subdirectory of your home directory (which is probably what you did but worth a try :)
* What version of Linux are you using? It shouldn't matter a great deal but it might be helpful to know that information.

**Comment by ajit-fawade** [comment]
It is failing on `docker-compose up`.
My Linux distro and version: Ubuntu 18.04.1 LTS.

These things I tried to do it again:
- Taken a new clone of the repo.
- Deleted all the docker containers and images.
- `docker-compose build`

These are the last steps of `docker-compose build`
Step 26/28 : USER $USER
 ---> Running in 36176c33e197
Removing intermediate container 36176c33e197
 ---> 3d9b48b385b8
Step 27/28 : EXPOSE 5000
 ---> Running in e9ae36c7734c
Removing intermediate container e9ae36c7734c
 ---> 752f7c42095c
Step 28/28 : CMD foreman start
 ---> Running in 995fe1dd5f0d
Removing intermediate container 995fe1dd5f0d
 ---> c9dbac1e045f
Successfully built c9dbac1e045f
Successfully tagged debug_web:latest

As per the given instructions, I tried running .`/run rake secret` in a separate console. It was showing the same progress as `docker-compose build`

After finishing `docker-compose build`, I ran `docker-compose up` and I got the above error.

**Comment by ericschultz** [comment]
@ajit-fawade thanks for the log. Sadly, I'm not seeing anything that could explain this. I'm not sure where to go from here. You said you created the `tmp` directory correct on your own, correct? That shouldn't be an issue but I don't know.

As an alternative, you could install all the packages on your own system and not bother running it in Docker. The real advantage of Docker for development is consistency. Let me know if you need anything help doing that.

Again, I'm really sorry about this.

**Comment by ajit-fawade** [comment]
Thanks, @ericschultz . I'll definitely try it by installing all the packages on my system. I'll also try it on a different platform. I'll let you know if I need any help. Thanks for being attentive.

**Comment by ericschultz** [comment]
@ajit-fawade did you have any luck with this?

**Comment by ajit-fawade** [comment]
Yeah. I changed the permission of the project repository by accessing the console through `docker-compose run -u root  web /bin/bash`

**Comment by ajit-fawade** [comment]
My console 1 is flooded with these statements:
**Delayed::Backend::ActiveRecord::Job Load (1.8ms)** 

and I am not able to submit the initial nonprofit and info form.

**Comment by ajit-fawade** [comment]
@ericschultz any updates?

**Comment by ericschultz** [comment]
@ajit-fawade really sorry, there's a bug-fix that I realized needs to be backported to this branch. I'm off until Tuesday but I'll do it then and let you know when it's done.

**Comment by ajit-fawade** [comment]
Sounds good.

**Comment by ericschultz** [comment]
@ajit-fawade I backported the fix to this branch and it works now. I rebased though so you'll have to do a forced git pull: `git pull -f`. You I think you should be able to start from `./run npm run watch` instruction.

**Comment by ajit-fawade** [comment]
Thanks, @ericschultz. I'll do the needful.

**Comment by ajit-fawade** [comment]
@ericschultz I followed your instructions given in the above comment but still, I am not able to submit the form.

**Comment by ericschultz** [comment]
@ajit-fawade I'm really getting pretty stumped here. Is the api request going to http://localhost:5000/api/v1/nonprofit?

**Comment by ajit-fawade** [comment]
Yes. The API request goes to http://localhost:5000/api/v1/nonprofit.
It is working now.
Thanks for your help @ericschultz

**Comment by ericschultz** [comment]
Fantastic! I'm sorry about the headache, I'm still not sure what caused the original issue related to permissions. If you ever stumble on any other clues to that, please do share them so we can figure out how to prevent it for others. Closing this issue for now.

**Comment by ericschultz** [comment]
@ajit-fawade btw, I'd love to find out what your plans are for Houdini. It's always exciting to hear about new use-cases!

**Comment by ajit-fawade** [comment]
I work for [doGood.](https://you.dogood.io) and we are planning to use Houdini project as a crowdfunding platform. I guess you had a conversation with doGood CEO Mr. Adam Harriss regarding the same.

**Comment by ericschultz** [comment]
@ajit-fawade that's very cool! We're looking forward to seeing the feature you come up with and upstreaming it into Houdini!
