### ISSUE TITLE
[FEATURE] Add a `roles` attribute to `user` objects

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#963]
Currently, there's no way to know what roles a user has. This is particularly a problem when we want to know what nonprofit the current user belongs to.

**Describe the solution you'd like**
Create a new role json partial which has

* the id of the role
* the name
* the host, which is a nonprofit or campaign
* the user itself

On the user json partial add a `roles` object which lists all of the roles the user has.

**Comment by wwahammy** [comment]
@clarissalimab: thoughts?

**Comment by clarissalimab** [comment]
Makes sense to me :+1:

**Comment by MaiconMares** [comment]
Dear @wwahammy I am from University of Brasilia, I've joined into Houdini project and I am excited to start contributing on the issues. It will be my first contribution!

**Comment by wwahammy** [comment]
@MaiconMares welcome to Houdini! We're glad to have you involved!
