### ISSUE TITLE
[FEATURE] Create `/api/nonprofit/:nonprofit_id/roles` for seeing the list of users with a role on a nonprofit

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#964]
Depends on #963 

Currently there's no way to see what roles and users that are associated with a nonprofit.

`/api/nonprofit/:nonprofit_id/roles` would list those roles.

**Comment by wwahammy** [comment]
Thoughts @clarissalimab?

**Comment by KalebeLopes** [comment]
Hi @wwahammy! @JoaoVitorFarias and i are students at the University of Brasilia and we are excited to contribute to this issue!
