### ISSUE TITLE
[FEATURE] Rename `subtransaction_payments` to `payments`

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#967]
Currently, each `Subtransaction` has many `subtransaction_payments`. This name is redundant and only really exists because we have a legacy entity already called Payment. For simplicity, let's just rename `subtransaction_payments` to `payments`.

**Comment by clarissalimab** [comment]
That would make it easier to understand, I support it.

**Comment by MaiconMares** [comment]
Hi, I and @alan-ms are gonna be working in this issue, but we have some doubts. We want to know if the problem requires that `subtransaction_payments` entity and all its dependencies have to be renamed or it's needed just to rename its name on the places that `subtransaction_payments` are called. Thank you for your attention!
